<feat>backend: setup winston in the backend
ValantineSuh/Budget-Expense-2 pull request #25
Opened 2024-04-17 16:37 UTC by Arielpetit

Please @stephane-segning and @ValantineSuh review this

2024-04-17 16:55 UTC, stephane-segning requested changes

2024-04-17 16:55 UTC, stephane-segning commented on expense-backend/src/index.js
This is file is auto-generated. Please remove it

2024-04-17 16:55 UTC, stephane-segning commented on expense-backend/src/index.ts
> +});
Please extract this into another file

2024-04-18 11:01 UTC, Arielpetit commented
Fixed

2024-04-22 09:30 UTC, stephane-segning requested changes
Please cancel all changes not related to the Backend.

2024-04-22 10:48 UTC, closed without merging